#!/usr/bin/python3
##
## EPITECH PROJECT, 2022
## main
## File description:
## main for 105torus
##

import sys
import global_variable as gb
from secant import secant
from bisection import bisection
from newton import newton
from usage import usage


def rigor(argv):
    if len(sys.argv) == 2 and sys.argv[1] == "-h":
        usage()
        exit(0)
    elif (len(sys.argv) != 8):
        print("Left arguments, for more information -h\n")
        exit(84)
    elif (len(sys.argv) == 1):
        print("Need arguments use -h")
        exit(84)
    elif (sys.argv[7] < '0'):
        print("Error")
        exit(84)
    i = 1
    while i < 8:
        try: int(sys.argv[i])
        except:
            print("Error, the parameters aren't int")
            exit(84)
        i+=1
    if (i == 8):
        gb.init()
    else:
        print("Error in arguments, for more information -h\n")
        exit(84)

rigor(sys.argv)

if gb.opt == 1:
    bisection(gb.n)
elif gb.opt == 2:
    newton(gb.n)
elif gb.opt == 3:
    secant(gb.n)
else:
    exit(84)



